import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./component/nav";
import Footer from "./component/footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "timo.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <header>
    <Nav />
  </header>

        {children}

        <footer>
          {/* <Footer /> */}
        </footer>
      </body>
    </html>
  );
}
