name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  

      - name: Setup Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Includes 'next export' for static export

      - name: Add .nojekyll
        run: touch out/.nojekyll  # Ensure the correct output folder

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: out  # Static output folder
